version: '3.8'
services:
  whisper-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data/uploads:/app/data/uploads
    environment:
      # disable python stdout buffering.
      - PYTHONUNBUFFERED=1
